-- AlterTable
ALTER TABLE "NameBasic" ALTER COLUMN "birthYear" SET DEFAULT '0',
ALTER COLUMN "birthYear" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "deathYear" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "TitleBasic" ALTER COLUMN "startYear" SET DEFAULT '0',
ALTER COLUMN "startYear" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "endYear" SET DEFAULT '0',
ALTER COLUMN "endYear" SET DATA TYPE VARCHAR(255);
